############ ATTACK ##########
exp_name: progan_debug_0
syn_data_path: data/celebAhuge_positive_64
pos_data_dir: data/celebAhuge_positive
neg_data_dir: data/celebAhuge_negative
data_num: 1024
K: 1
BATCH_SIZE: 32


############ METRICS #########s
