############ ATTACK ##########
exp_name: progan_debug_2
syn_data_path: ersecki-thesis/syn_data/dcgan/png_images/_2023_05_20__17_37_36
pos_data_dir: data/celebAhuge_positive
neg_data_dir: data/celebAhuge_negative
data_num: 20000
K: 1
BATCH_SIZE: 32


############ METRICS #########s
