############ ATTACK ##########
exp_name: progan_debug_1
syn_data_path: ersecki-thesis/syn_data/dcgan/jpg_images/_2023_05_10__10_28_53
pos_data_dir: data/celebAhuge_positive
neg_data_dir: data/celebAhuge_negative


############ METRICS #########s
