############ ATTACK ##########
exp_name: privPGGAN_2040_5_2_new
syn_data_path: ersecki-thesis/syn_data/privPGGA/png_images/_2023_06_12__17_56_39
pos_data_dir: data/celebAhuge_positive
neg_data_dir: data/celebAhuge_negative
K: 1
BATCH_SIZE: 64


############ METRICS #########s
