############ ATTACK ##########
exp_name: privDCGAN
syn_data_path: ersecki-thesis/syn_data/privDCGAN/png_images/privacy_ratio-N_splits
pos_data_dir: data/celebAhuge_positive
neg_data_dir: data/celebAhuge_negative
hyperparameter_search: True
K: 1
BATCH_SIZE: 64


############ METRICS #########s
