############ ATTACK ##########
exp_name: progan_debug_5
syn_data_path: ersecki-thesis/syn_data/dcgan/jpg_images/_2023_05_16__14_32_56
pos_data_dir: data/celebAhuge_positive
neg_data_dir: data/celebAhuge_negative


############ METRICS #########s
