############ ATTACK ##########
exp_name: progan_debug_2
syn_data_path: ersecki-thesis/syn_data/dcgan/jpg_images/_2023_05_14__18_22_12
pos_data_dir: data/celebAhuge_positive
neg_data_dir: data/celebAhuge_negative


############ METRICS #########s
